-- MySQL Script generated by MySQL Workbench
-- lun. 09 déc. 2019 22:16:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`myMovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`myMovies` (
  `idmovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `director` VARCHAR(145) NOT NULL,
  `released` DATE NOT NULL,
  `isUnder16` TINYINT(1) NULL,
  `poster_url` LONGTEXT NULL,
  `rate` INT NULL,
  `sum_up` LONGTEXT NULL,
  `genre` ENUM('Comedy', 'Thriller', 'Sci-Fi', 'Horror', 'Action') NULL,
  PRIMARY KEY (`idmovie`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;